In [1]:
import numpy as np
import tensorflow as tf

## **Tensor 생성**
- []
  - List 생성

In [2]:
[1, 2, 3]

[1, 2, 3]

In [3]:
[[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

### **Array 생성**
- tuple이나 list 둘 다 np.array()로 씌어서 array를 만들 수 있음

In [5]:
arr = np.array([1,2,3])

In [6]:
arr.shape

(3,)

In [8]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [9]:
arr.shape

(2, 3)

### **Tensor 생성**
 - tf.constant()
  - list → Tensor

In [10]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

- tf.constant()
 - tuple → Tensor

In [11]:
tf.constant(((1, 2, 3), (1, 2, 3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

- tf.constant()
 - Array → Tensor

In [12]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [13]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

### **Tensor에 담긴 정보 확인**
 - shape 확인

In [14]:
tensor.shape

TensorShape([3])

- data type확인
 - 주의: Tensor 생성 할 때도 data type을 정해주지 않기 때문에 data type에 대한 혼동이 올 수 있음
 - Data Type에 따라 모델의 무게나 성능 차이에도 영향을 줄 수 있음

In [15]:
tensor.dtype

tf.int32

- data type 정의

In [17]:
tensor = tf.constant([1, 2, 3], dtype= tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

- data type 변환
 - Numpy에서 astype()을 주었듯이. TensorFlow에서는 tf.cast를 사용

In [19]:
arr = np.array([1,2 ,3], dtype = np.float32)

In [21]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [22]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [23]:
tf.cast(tensor, dtype= tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

- Tensor에서 Numpy 불러오기
 - .numpy()

In [24]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

- Tensor에서 Numpy 불러오기
 - np.array()

In [25]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

type()를 사용하여 numpy array로 변환된 것 확인

In [27]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [26]:
type(tensor.numpy())

numpy.ndarray

## **난수 생성**
- Normal Distrinution은 중심극한 이론에 의한 연속적인 모양
- Uniform Distribution은 중심 극한 이론과는 무관하며 불연속적이며 일정한 분표
- numpy에서는 normal distrinution을 기본적으로 생성
 - np.random.randn()

In [30]:
np.random.randn(9)

array([ 2.13006444, -0.04314625, -0.16501895,  0.11418107, -0.01776535,
       -1.16553762, -0.83329268, -0.83411017, -1.52790838])

- tf.random.normal
 - TensorFlow에서 Normal Distribution

In [31]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.2749757 , -0.8216205 , -0.13790417],
       [ 1.5014989 ,  0.8381533 , -1.47129   ],
       [-0.6260648 ,  0.86464334,  0.53650534]], dtype=float32)>

- tf.random.uniform
 - TensorFlow에서 Uniform Distribution

In [32]:
tf.random.uniform([4, 4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.23767507, 0.2623061 , 0.8416101 , 0.52423024],
       [0.91858876, 0.97755   , 0.05365121, 0.26996326],
       [0.73106873, 0.9709511 , 0.7373885 , 0.49552262],
       [0.02914262, 0.4688933 , 0.5914353 , 0.7272303 ]], dtype=float32)>